### ISSUE TITLE
Mechanism addition

### ISSUE THREAD

**Issue by herofmm** [jiweiqi/CollectionOfMechanisms#12]
Hi, I find this repository is very useful.  

Can I ask to add some more mechanisms?  There are a couple of mechanisms I am interested in (Aramco and NUIG), but I cannot convert the CHEMKIN formats to CTI or YAML.  Could you help to convert them to a cantera format?

You can find the chemkin file format in the following site. Thank you in advance.

https://www.nuigalway.ie/combustionchemistrycentre/mechanismdownloads/

**Comment by jiweiqi** [comment]
What's the issue in converting the mechanism?

**Comment by herofmm** [comment]
> What's the issue in converting the mechanism?

Yes, it fails.  When I tried to convert them using ck2cti, I got error for both mechanisms.  I am using the latest Cantera with Python 3.8.5.

When I executed with the following command, I got the next error message.  

ck2cti --input=NUIGMech1.1.MECH --thermo=NUIGMech1.1.THERM --transport=NUIGMech1.1.TRAN --permissive -d

---------------------------------------------------------------
FAILED.

*******************************************************************************
InputFileError thrown by Kinetics::checkDuplicates:
Undeclared duplicate reactions detected:
Reaction 5: H2 + M <=> 2 H + M
Reaction 1: 2 H + O2 <=> H2 + O2
*******************************************************************************
---------------------------------------------------------------

When I tried to convert Aramco 3.0 Mechanism, I got the following error message

ck2cti --input=AramcoMech3.0.MECH --thermo=ARAMCOMECH30.THERM --transport=AramcoMech3.0.TRAN --permissive -d

-------------------------------------------------
Traceback (most recent call last):
  File "/opt/cantera/lib/python3.8/site-packages/cantera/ck2cti.py", line 874, in __init__
    geometry = int(geometry)
ValueError: invalid literal for int() with base 10: '0.000'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/cantera/bin/ck2cti", line 11, in <module>
    load_entry_point('Cantera==2.6.0a2', 'console_scripts', 'ck2cti')()
  File "/opt/cantera/lib/python3.8/site-packages/cantera/ck2cti.py", line 2363, in script_entry_point
    main(sys.argv[1:])
  File "/opt/cantera/lib/python3.8/site-packages/cantera/ck2cti.py", line 2334, in main
    surfaces = Parser.convertMech(inputFile, thermoFile, transportFile,
  File "/opt/cantera/lib/python3.8/site-packages/cantera/ck2cti.py", line 2264, in convertMech
    parser.parseTransportData(lines, transportFile, 1)
  File "/opt/cantera/lib/python3.8/site-packages/cantera/ck2cti.py", line 2009, in parseTransportData
    self.speciesDict[speciesName].transport = TransportData(*data, comment=comment)
  File "/opt/cantera/lib/python3.8/site-packages/cantera/ck2cti.py", line 876, in __init__
    raise InputParseError("Bad geometry flag '{0}' for species '{1}', is the flag a float "
cantera.ck2cti.InputParseError: Bad geometry flag '0.000' for species 'AR', is the flag a float or character? It should be an integer.
---------------------------------------------------------------------

**Comment by jiweiqi** [comment]
A little bit busy those days. Do you mind asking for help in Cantera google group?

**Comment by herofmm** [comment]
> A little bit busy those days. Do you mind asking for help in Cantera google group?

Thank you for pointing me out there.  I was able to find CTI files which I am looking for.  Thank you a bunch!
